### ISSUE TITLE
Error (Line 10)

### ISSUE THREAD

**Issue by v4ld3r** [gyoisamurai/GyoiThon#11]
Hi!
This message appears to me when I try to run the program

root@kali:~/Pentest/GyoiThon# python gyoithon.py 
Traceback (most recent call last):
  File "gyoithon.py", line 10, in <module>
    from urllib.request import urlopen
ImportError: No module named request

can you help me?? 

Thanks

**Comment by 13o-bbr-bbq** [comment]
Hi, @v4ld3r 
Maybe, your python environment doesn't include `urllib`.
Did you install `urllib` module?

**Comment by eudomoniacc** [comment]
script is compatible with python3 but there is no ssl "https" support

**Comment by gyoisamurai** [comment]
Hi, @eudomoniacc 
We changed from `urllib` to `urllib3` in `gyoithon.py` and `GyoiClassifier.py`.
Please, try again.

**Comment by gyoisamurai** [comment]
@v4ld3r 
Please try again after installing `urllib3`.
