### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by M0dred** [gyoisamurai/GyoiThon#21]
I see the new function "CVE" detect but  README.md has not been updated.

**Comment by gyoisamurai** [comment]
Yes, this is new version.
Usage is below.
https://github.com/gyoisamurai/GyoiThon/wiki/Usage

But, now this contents is Japanese only.
I'll add English contents soon!!

**Comment by gyoisamurai** [comment]
I wrote the detail of new functions in English.  
Please, check it!!

https://github.com/gyoisamurai/GyoiThon
