### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by M0dred** [gyoisamurai/GyoiThon#22]
root@xxx:/opt/GyoiThon# python3 gyoithon.py 

Traceback (most recent call last):
  File "gyoithon.py", line 158, in <module>
    show_banner(utility)
  File "gyoithon.py", line 76, in show_banner
    utility.print_message(NONE, banner)
  File "/opt/GyoiThon/util.py", line 82, in print_message
    print(NOTE_GREEN + message + ENDC)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 82-91: ordinal not in range(128)
![20181119161043](https://user-images.githubusercontent.com/10797376/48687473-bd591380-ec15-11e8-935d-3fc649c3eea9.png)

root@xxx:/opt/GyoiThon# uname -a
Linux 4.17.0-kali3-amd64 #1 SMP Debian 4.17.17-1kali1 (2018-08-21) x86_64 GNU/Linux

**Comment by fargusplumdoodle** [comment]
Fixed!
Turns out its a locales issue
https://github.com/gyoisamurai/GyoiThon/issues/35
