### ISSUE TITLE
ImportError: No module named modules.Gyoi_CloudChecker

### ISSUE THREAD

**Issue by M0dred** [gyoisamurai/GyoiThon#27]
root@kali:/opt/GyoiThon# python gyoithon.py
Traceback (most recent call last):
  File "gyoithon.py", line 14, in <module>
    from modules.Gyoi_CloudChecker import CloudChecker
ImportError: No module named modules.Gyoi_CloudChecker
root@lolicen:/opt/GyoiThon# pip3 install modules.Gyoi_CloudChecker
Collecting modules.Gyoi_CloudChecker
  Could not find a version that satisfies the requirement modules.Gyoi_CloudChecker (from versions: )
No matching distribution found for modules.Gyoi_CloudChecker

**Comment by gyoisamurai** [comment]
Had you executed the following command in Installation step?

```
> git clone https://github.com/gyoisamurai/GyoiThon.git
```

When you execute above command, required modules for GyoiThon are installed.
