### ISSUE TITLE
requirements.txt is unnecessary strict

### ISSUE THREAD

**Issue by blshkv** [gyoisamurai/GyoiThon#30]
Hi, I'm porting your tool to Pentoo Linux and facing the problem with other tools which require not so decent versions and might not work/tested with the latest yet.

The requirements seem unnecessary strict and require the latest version exclusively:
https://github.com/gyoisamurai/GyoiThon/blob/30aae110164117b6430f1325638c2e763377184a/requirements.txt#L1-L13

Specifically, the following are the troubled packages:
- gnuradio (supports python 2.x only)
- matplotlib-3.0.3 supports python 3.x only
- requests, does not support urllib3 yet
- may be others.

Could you relax dependences, do not use ```==``` and replace with ```>=``` and only require a specific version **IF** it is **really** necessary?

**Comment by gyoisamurai** [comment]
@blshkv Thank you for your support. I've fixed requirement.txt.

**Comment by blshkv** [comment]
Cheers
