### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by 007scorpio** [gyoisamurai/GyoiThon#4]
How can i make it to pick hostname instead of IP ADDR

**Comment by gyoisamurai** [comment]
@007scorpio Thanks for your issue.  
GyoiThon of current version can not pick hostname.  
But, we think that the function of to pick hostname is necessary. 

We'll correspond to pick hostname by April 9, please just a minutes.

**Comment by pemlane** [comment]
upon running the script this the error i get, any help?
#python gyoithon.py
Traceback (most recent call last):
 File "gyoithon.py", line 10, in <module>
from urllib.request import urlopen
ImportError: No module named request

**Comment by kelvynk01** [comment]
Having issues with my version of python. Apparently, nearly all modules cannot be imported.
How can you pls assist me ?

**Comment by 13o-bbr-bbq** [comment]
@kelvynk01 
What's your python's version? I can run the gyoithon using "Python 3.6.1".
And, I'm using the "Anaconda3". It includes many modules.
https://repo.continuum.io/

**Comment by eudomoniacc** [comment]
Ssl support is a must to be added i think
