### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by pemlane** [gyoisamurai/GyoiThon#6]
**_

upon running the script this the error i get, any help?

_**
#python gyoithon.py
Traceback (most recent call last):
File "gyoithon.py", line 10, in
from urllib.request import urlopen
ImportError: No module named request

**Comment by gyoisamurai** [comment]
@pemlane `urllib` is default library of python3. Is your python environment python3?
We confirmed that gyoithon works with `Python 3.6.1`.

**Comment by pemlane** [comment]
after setting python environment to python3

Traceback (most recent call last):
  File "gyoithon.py", line 9, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by pemlane** [comment]
Thanks worked

**Comment by pemlane** [comment]
worked, thanks
