### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ddddyyy** [gyoisamurai/GyoiThon#7]
i set the file host 172.16.62.190 80 /var/www/html

some error happened 

Traceback (most recent call last):
  File "gyoithon.py", line 228, in <module>
    products = classifier.analyzer(ip_list[idx], int(port_list[idx]), ip_list[idx])
  File "./classifier4gyoithon/GyoiClassifier.py", line 95, in analyzer
    fin = codecs.open(logfile_path, 'r', encoding='utf-8')
  File "/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/root/GyoiThon/classifier4gyoithon/../http://172.16.62.190:80/'

**Comment by gyoisamurai** [comment]
@ddddyyy Yesterday, we fixed the bug at `GyoiClassifier.py`. Can you retry to use latest source code?

**Comment by ddddyyy** [comment]
oh, I downloaded the source code last Friday,  thanks for your replay!

**Comment by Manidills** [comment]
Still getting error !!!
